import type { Metadata } from "next";
import "../styles/template.scss";
// import "../styles/templates.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-bs-theme="dark">
      <body className="">{children}</body>
    </html>
  );
}
